export { config } from './config'
export { convertAAX, splitToChapters } from './converter'
export { parseAaxFile } from './aax-parser'
export type { AaxFileInfo, SampleEntry } from './aax-parser'
export { decryptSample, deriveKeys, parseActivationBytes, validateActivationBytes } from './aax-decryptor'
export type { DecryptionKeys } from './aax-decryptor'
export type { ConversionOptions, ConversionResult, BookMetadata, Chapter, AAXConfig } from './types'
export { getActivationBytesFromAudibleCli, isValidActivationCode } from './utils/activation'
